[package]
name = "choral_writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.22"
rand = "0.8.5"
twelve_et = {path = "/Users/benjaminhaase/development/Personal/twelve_et"}
